
/**
 * Game subscribes to gameId events and handles them posting moves
 * generated by player object that must implement two methods:
 * 
 * getNextMove(array of uciMoves) returns uciMove
 * getReply(chat event) returns chat message  
 * 
 */

const chalk = require('chalk')
const personalites = require('./personalities')


class Game {

  /**
   * Initialise with interface to lichess.
   */
  constructor(api, name, player) {
    this.api = api;
    this.name = name;
    this.player = player;
  }

  async start(gameId) {
    this.gameId = gameId
    this.willAcceptDraw = false
    this.api.streamGame(gameId, (event) => this.handler(event));
    this.isMoving = false
    this.isAcceptingDraws = false
    this.hasDrawOffer = false
    this.previousMoves = ''
    this.lichessBotName = process.env.LICHESS_BOT_NAME
    this.ratedWizPlayer = process.env.RATED_WIZ_PLAYER

    // this variable is used to be sure that if the system restarted we 
    // don't prematurely decline a draw when the system doesn't actaully know 
    // if it really should draw or not
    this.drawShouldWaitForMove = true
  }

  async handler(event) {
    console.log(chalk.yellow('event: ' + event.type))
    switch (event.type) {
      case "chatLine":
        this.handleChatLine(event)
        break;
      case "gameFull":
        // console.log(event)
        await this.setupGame(event)
        this.handleGameState(event.state)
        break;
      case "gameState":
        // console.log(event)
        this.handleGameState(event)
        break;
      default:
        console.log("Unhandled game event : " + JSON.stringify(event));
    }
  }

  async setupGame(event) {
    this.color = this.playingAs(event)
    this.rated = event.rated
    if (event.state.bdraw || event.state.wdraw) {
      console.log('A draw was requested')
      this.hasDrawOffer = true
    }
    await this.findAndSetWizPlayer()
  }

  async handleGameState(gameState) {
    if (gameState.status === 'draw') return

    if(!this.isMoving) {
      this.isMoving = true
      await this.playNextMove(gameState)
      this.isMoving = false
    }
   }

  handleChatLine(event) {
    if (event.username === 'lichess' && event.room === 'player' && 
        event.text.includes('offers draw')
    ) {
        console.log('A draw was requested')
        this.hasDrawOffer = true
    
        if (this.hasDrawOffer && this.willAcceptDraw && !this.isMoving)  {
          this.api.acceptDraw(this.gameId)
          return
        }

        if (this.hasDrawOffer && !this.willAcceptDraw && !this.isMoving 
          && !this.drawShouldWaitForMove
        )  {
          this.api.declineDraw(this.gameId)
          return
        }
    }

    if (event.username === 'lichess' && event.room === 'player'  &&
        event.text.includes('declines draw')
    ) {
      console.log('Draw was declined')
      this.hasDrawOffer = false
    }

    if (event.username !== this.name) {
      const message = event.text.toLowerCase()
      if (this.wizPlayer == '') {
        const cmp = personalites.fuzzySearch(message)
        if ( !cmp ) {
          this.api.chat(this.gameId, 'player', "Sorry, I don't know that opponent");
          return
        }

        this.wizPlayer = personalites.getProperName(cmp.name)
        this.api.chat(this.gameId,'player', 
          `Playing as ${this.wizPlayer}. Wiz Rating ${cmp.rating}. ${cmp.summary}`
        );
        this.api.chat(this.gameId, 'spectator', `Playing as ${this.wizPlayer}`);

        this.playNextMove()
      }
    }
  }

  async findAndSetWizPlayer() {
    let chatPlayer = await this.getWizPlayerFromChat()
    
    // If no opponent has been set in chat and this is a rated game set
    // the game to play as the default Wiz Player
    if ((chatPlayer === '' || chatPlayer === 'should ask who to play') &&  this.rated) {
      this.setWizPlayer(this.ratedWizPlayer)
      return
    }


    
    // This means chat has no messages at all so we should ask who the player wants to play
    if (chatPlayer === 'should ask who to play' && !this.rated) {
      this.api.chat(
        this.gameId, 
        'player', 'Who would you like to play? Give me a name or a rating number from 1 to 2750.'
      );
      this.api.chat(this.gameId, 'spectator', 'Waiting for opponent selection');
      // clear this for next if
      chatPlayer = ''
    } 


    // No player found in chat setting wizPlayer, still waiting to be told who to play as
    if (chatPlayer === '') {
      console.log(chalk.red(`No player found for game ${this.gameId}`))
      // probably not necessary but just for safety go ahead and set wizPlayer to empty string
      this.wizPlayer = ''
      return 
    } 
    
    // if gauntlet passed, a player was found in the chat
    this.wizPlayer = chatPlayer
    console.log(chalk.magenta(`Playing ${this.gameId} as ${this.wizPlayer}`))
  }

  setWizPlayer(wizPlayer) {
    this.wizPlayer = wizPlayer
    this.api.chat(this.gameId, 'player', `Playing as ${wizPlayer}`);
    this.api.chat(this.gameId, 'spectator', `Playing as ${wizPlayer}`);
    // this.playNextMove(this.previousMoves)
  }

  async getWizPlayerFromChat() {
    const {data: chatLines } = await this.api.getChat(this.gameId)
    // handle response errors

    // we need to ask them who they wan to play
    const wizMessages = chatLines.filter(line => line.user === this.lichessBotName)
    if (wizMessages.length === 0) return 'should ask who to play'

    // no opponent set in chat yet
    const playAsMessages = wizMessages.filter(line => line.text.includes('Playing as'))
    if (playAsMessages.length === 0) return ''

    const opponent = 
      playAsMessages[0].text.match(/Playing as [A-Za-z0-9]*/)[0].replace('Playing as ', '')

    return opponent
  }

  async playNextMove(gameState) {
    // cache the moves if we end up not moving right due to missing Wiz Player
    if (gameState) this.previousMoves = gameState.moves
    const previousMoves = this.previousMoves

    // if we are still under 15 moves (30 half moves) any draws can be immediately accepted
    if (previousMoves.length <= 30) this.drawShouldWaitForMove = false
   
    const moves = (previousMoves === "") ? [] : previousMoves.split(" ");

    // if it's not the bots turn then exit
    if (!isTurn(this.color, moves)) return

    const moveData = await this.player.getNextMove(moves, this.wizPlayer, this.gameId);
    
    // no move was found or move setup was invalid, go about your business
    if (!moveData) return 

    const { move, willAcceptDraw } = moveData
    this.willAcceptDraw = willAcceptDraw
    this.drawShouldWaitForMove = false
    
    
    if (this.hasDrawOffer && this.willAcceptDraw)  {
      // this will keep susequent events from triggering draw request
      this.willAcceptDraw=false
      await this.api.acceptDraw(this.gameId)
      return
    }
 

    console.log(this.name + " as " + this.color + " to move " + move);
    await this.api.makeMove(this.gameId, move)
  }

  playingAs(event) {
    return (event.white.name === this.name) ? "white" : "black";
  }

}

function isTurn(color, moves) {
  var parity = moves.length % 2;
  return (color === "white") ? (parity === 0) : (parity === 1);
}


module.exports = Game;
