#!/bin/bash
# Builds a win32 and linux version of binary for testing stdio

# GOOS=windows GOARCH=386 go build -o enginewrap.exe  main.go 
# GOOS=linux go build -o enginewrap  main.go 

GOOS=windows GOARCH=386 go build -o simpleout.exe  main2.go 
GOOS=linux go build -o simpleout  main2.go 


