
/**
 * Game subscribes to gameId events and handles them posting moves
 * generated by player object that must implement two methods:
 * 
 * getNextMove(array of uciMoves) returns uciMove
 * getReply(chat event) returns chat message  
 * 
 */

const chalk = require('chalk')
const personalites = require('../../personalities')


class Game {

  /**
   * Initialise with interface to lichess.
   */
  constructor(api, name, player) {
    this.api = api;
    this.name = name;
    this.player = player;
  }

  async start(gameId) {
    this.gameId = gameId
    // this.chatHistory = this.getChatHistory()
    this.wizPlayer = await this.getWizPlayerFromChat()
    if (this.wizPlayer == '') {
      console.log(chalk.red(`No player found for game ${gameId}`))
    } else {
      console.log(chalk.magenta(`Playing ${this.gameId} as ${this.wizPlayer}`))
    }

    this.api.streamGame(gameId, (event) => this.handler(event));
  }

  handleChatLine(event) {
    if (event.username !== this.name) {
      const message = event.text.toLowerCase()
      if (this.wizPlayer == '') {
        let opponent = message.replace('play ', '').replace('as ', '').trim()
        this.wizPlayer = personalites.getProperName(opponent)
        
        if (!this.wizPlayer) { 
          this.api.chat(this.gameId, 'player', "Sorry, I don't know that opponent");
        } else {
          this.api.chat(this.gameId, 'player', `Playing as ${this.wizPlayer}`);
          this.api.chat(this.gameId, 'spectator', `Playing as ${this.wizPlayer}`);
          this.playNextMove(this.previousMoves)
        } 
      }
    }
  }

  // Check the spectator chat (via HTML page) for a Wiz Player setting
  async getWizPlayerFromChat() {
    const gamePage = await this.api.gamePage(this.gameId)
    const re = /"u":"yeoldwiz","t":"Playing as [A-Za-z0-9\.]*/g
    const opponentData = gamePage.data.match(re)
    let opponent = ''
    if (opponentData == null) {
      return ''
    }
    opponent = opponentData[0].replace('"u":"yeoldwiz","t":"Playing as ', '')
    return opponent
  }


  handler(event) {
    // console.log(chalk.yellow(event.type))
    switch (event.type) {
      case "chatLine":
        this.handleChatLine(event);
        break;
      case "gameFull":
        this.colour = this.playingAs(event);
        this.playNextMove(event.state.moves);
        break;
      case "gameState":
        this.playNextMove(event.moves);
        break;
      default:
        console.log("Unhandled game event : " + JSON.stringify(event));
    }
  }

  async playNextMove(previousMoves) {
    // cache the moves if we end up not moving right due to missing Wiz Player
    this.previousMoves = previousMoves
    
    
    const moves = (previousMoves === "") ? [] : previousMoves.split(" ");
    if (this.isTurn(this.colour, moves)) {
      const nextMove = await this.player.getNextMove(moves, this.wizPlayer, this.gameId);
      if (nextMove) {
        console.log(this.name + " as " + this.colour + " to move " + nextMove);
        this.api.makeMove(this.gameId, nextMove);
      }
    }
  }

  playingAs(event) {
    return (event.white.name === this.name) ? "white" : "black";
  }

  isTurn(colour, moves) {
    var parity = moves.length % 2;
    return (colour === "white") ? (parity === 0) : (parity === 1);
  }
}

module.exports = Game;
