#!/bin/bash

# docker run $1 --rm -it -v $(pwd):/opt/yeoldwiz thinktt/yeoldwiz /bin/bash
# docker run $1 --rm -v $(pwd):/opt/yeoldwiz thinktt/yeoldwiz ./node main.js
# docker run --rm -v $(pwd):/opt/yeoldwiz thinktt/yeoldwiz wine enginewrap.exe
# docker run -it thinktt/yeoldwiz /bin/bash
# docker run $1 --rm -v $(pwd):/opt/yeoldwiz thinktt/yeoldwiz
# docker run --env-file ace.env -it thinktt/yeoldwiz /bin/bash
# docker run -it abcb4ef58afd /bin/bash

# docker run -it thinktt/yowapi /bin/sh
# docker run -it -p 6000:5000 --network=mongonet --name yowapi ace:5000/yowapi:latest /bin/sh
# docker run -d -p 6000:5000 --network=mongonet --name yowapi ace:5000/yowapi:latest 

# docker run -it --rm \
# -p 6000:5000 \
# -e MONGO_HOST=mongodb \
# --network mongonet \
# --name yowapi ace:5000/yowapi:latest \
# /bin/sh 

docker run -d --rm \
-p 6000:64355 \
-e MONGO_HOST=mongodb \
--network mongonet \
--name yowapi ace:5000/yowapi:latest \

echo "NOTICE after you run this you must connect it to proxynet manually"
echo "docker network connect proxynet yowapi"