#!/bin/bash

# Paths to the folders
folder1="assetsOld/cm/personalities/"
folder2="assets/cm/personalities/"

# Create sorted lists of checksums for both folders
find "$folder1" -type f -exec sha256sum {} \; | sort > folder1_checksums.txt
find "$folder2" -type f -exec sha256sum {} \; | sort > folder2_checksums.txt

# Compare the checksum files using diff
#diff folder1_checksums.txt folder2_checksums.txt

# Optionally remove the temporary checksum files
# rm folder1_checksums.txt folder2_checksums.txt
